version: '3.8'

services:
    app:
        container_name: poc-symfony-lit
        build: 
          context: .
          dockerfile: Dockerfile
        ports:
            - "9000:8000"
        volumes:
            - ./:/var/www/html
